# Generated by Django 5.2.8 on 2025-11-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_alter_loginuser_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='attribute_name',
        ),
    ]
