# Generated by Django 5.2.8 on 2025-11-07 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_alter_district_created_by_alter_district_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='propertytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_related', to='property_app.propertytype'),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='taluk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.taluk'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.attribute'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='public_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.publicproperty'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propertype_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicproperty',
            name='panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.panchayat'),
        ),
        migrations.AlterField(
            model_name='publicproperty',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicproperty_related', to='property_app.propertytype'),
        ),
        migrations.AlterField(
            model_name='taluk',
            name='discrete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.district'),
        ),
    ]
