# Generated by Django 5.2.8 on 2025-11-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0005_alter_attribute_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='role_name',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='role_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('WRITER', 'WRITER'), ('VIEWER', 'VIEWER')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='LoginRole',
        ),
    ]
